ProjectCity2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('horoscope_app.urls')),
]

horoscope/urls.py
from django.urls import path
from horoscope import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:url>', views.get_sing_zodiac_by_date),
    path('<str:code>', views.get_sing_zodiac, name='sign_zodiac'),
    path('elements/', views.get_elements, name='get_elements'),
    path('elements/<str:code>', views.get_sing_by_element_name, name='get_sing_by_element_name'),
    path('calendar/', views.get_sing_zodiac_by_date, name='get_sing_zodiac_by_date'),
]

horoscope_app/urls.py
from django.urls import path
from horoscope_app import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexListView.as_view(), name='index'),
    path('<int:url>', views.get_sing_zodiac_by_date),
    path('<str:code>', views.get_sing_zodiac, name='sign_zodiac'),
    path('elements/', views.ElementsView.as_view(), name='get_elements'),
    path('elements/<str:code>', views.get_sing_by_element_name, name='get_sing_by_element_name'),
    path('calendar/', views.get_sing_zodiac_by_date, name='get_sing_zodiac_by_date'),
]

horoscope_app/models.py
from django.db import models
from datetime import date

# Create your models here.
class Forecast(models.Model):
    sing = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=5000, null=True)
    date_create = models.DateField(default=date.today)

    def __str__(self):
        return f'{self.sing} - {self.description}'


class Elements(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return f'{self.name}'


class ZodiakSing(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=45, unique=True)
    description = models.TextField(blank=True)
    date_from = models.DateField()
    date_to = models.DateField()
    elements = models.ForeignKey(Elements, on_delete=models.PROTECT)

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.name} - {self.code} - {self.description}'

horoscope_app/forms.py
from horoscope_app.models import ZodiakSing, Elements
from django.forms import ModelForm, DateInput

class ZodiakSingForm(ModelForm):
    class Meta:
        model = ZodiakSing
        fields = ['date_from']

        widgets = {
            "date_from": DateInput(attrs={
                'type': 'date',
                'class': 'form-conrol',
            })
        }

horoscope_app/views.py
from django.shortcuts import render, redirect
from horoscope_app.models import ZodiakSing, Elements, Forecast
from .forms import ZodiakSingForm
from django.db.models import Q
from django.views import generic
import requests, datetime

from django.core.management.base import BaseCommand
from django.db import transaction


#
# Как оптимизировать?
#
def have_forecast_today():
    if len(Forecast.objects.filter(sing='general')) != 0:
        if datetime.date.today() == Forecast.objects.filter(sing='general')[0].date_create:
            return True
    else:
        return False



@transaction.atomic  # инструмент управления транзакциями базы данных
def load_forecast():
    """Записывает прогноз в формате json в модель Forecast"""
    # если в Forecast нет прогноза за сегодня делаем запрос на получение
    have_forecast_today() # проверка есть ли прогноз на сагодня
    if not have_forecast_today():
        Forecast.objects.all().delete()  # очищаем базу данных перед тем как заполнить таблицу
        forecasts = get_forecast_for_api()
        to_create = []
        for forecast in forecasts:
            to_create.append(Forecast(
                sing=forecast['sing'],
                description=forecast['description'],
            ))
        Forecast.objects.bulk_create(to_create)


def get_forecast_for_api():
    """ Получаем прогноз по api """
    url = 'https://intense-badlands-65950.herokuapp.com/api/forecast/'  # Полный адрес эндпоинта
    headers = {'authorization': 'Token 16058768c24b66535820533ba5fabd3381cc8905',
               'content-type': 'application/json', }
    response = requests.get(url, headers=headers)  # Делаем GET-запрос
    # Поскольку данные пришли в формате json, переведем их в python
    response_on_python = response.json()
    return response_on_python


class IndexListView(generic.ListView):
    model = ZodiakSing
    # Определение имени шаблона и его расположения
    template_name = 'horoscope_app/index.html'

    def get_context_data(self, **kwargs):
        load_forecast()  # куда добавлять функцию для исполнения?
        context = super(IndexListView, self).get_context_data(**kwargs)
        context['forecast_general'] = Forecast.objects.get(sing='general')  # общий прогнроз для всх знаков
        context['forecast'] = Forecast.objects.all()
        context['today'] = datetime.date.today()
        return context


def get_sing_zodiac(request, code):
    """Вывод информации о каждом знаке"""
    zodiac_sing = ZodiakSing.objects.get(code=code)
    context = {
        'zodiac_sing': zodiac_sing,
        'forecast_zodiac_sing': Forecast.objects.get(sing=zodiac_sing.name),
        'zodiac_sings': ZodiakSing.objects.all(),
    }
    return render(request, 'horoscope_app/info_zodiac.html', context=context)


class ElementsView(generic.ListView):
    """Вывод 4х стихий"""
    model = Elements
    template_name = 'horoscope_app/get_elements.html'


def get_sing_by_element_name(request, code):
    context = {
        'zodiac_sings': ZodiakSing.objects.all(),
        'element': Elements.objects.get(code=code),
        'elements': ZodiakSing.objects.filter(elements_id=(Elements.objects.get(code=code).id)),
    }
    return render(request, 'horoscope_app/get_sing_by_element_name.html', context=context)


def search_sing_by_date(date):
    sign = ZodiakSing.objects.filter(
        Q(date_from__day__lte=date.day, date_from__month=date.month) |
        Q(date_to__day__gte=date.day, date_to__month=date.month)
    ).order_by('date_to').first()
    return sign.code


def get_sing_zodiac_by_date(request):
    error = ''
    if request.method == 'POST':
        form = ZodiakSingForm(request.POST)
        if form.is_valid():
            return redirect(f'/{search_sing_by_date(form.cleaned_data["date_from"])}')
        else:
            error = 'Некорректные данные'
    form = ZodiakSingForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'horoscope_app/calendar.html', context=data)

horoscope_app/templates/horoscope_app/calendar.html
{% extends 'base.html' %}

{% block title %}
Поиск знака зодиака по дате
{% endblock %}

{% load static %}
{% load my_filter %}

{% block cssadd %}
<link rel="stylesheet" href="{% static 'horoscope_app/css/index.css' %}">
{% endblock %}


{% block content %}
{% include 'includes/navbar.html' %}
<h1>Поиск знака зодиака по дате</h1>

<form method="post">
    {% csrf_token %}
    {{ form.date_from }}
    {{ form.text }}
    <span>{{ error }}</span>
    <button type="submit" class="btn btn-outline-info">Отправить</button>
</form>

{% endblock %}

horoscope_app/templates/horoscope_app/get_elements.html
{% extends 'base.html' %}

{% block title %} Элементы {% endblock %}

{% load static %}
{% load my_filter %}

{% block cssadd %}
<link rel="stylesheet" href="{% static 'horoscope_app/css/index.css' %}">
{% endblock %}


{% block content %}
{% include 'includes/navbar.html' %}
<h1>Элементы</h1>
<ul class="ul-style-2">
    {% for element in elements_list %}
        <li class='ul-li'><a class="btn btn-outline-dark" href="{% url 'get_sing_by_element_name' code=element.code %}">{{element.name}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

horoscope_app/templates/horoscope_app/get_sing_by_element_name.html
{% extends 'base.html' %}


{% block title %}
{{sign.title}}
{% endblock %}

{% load static %}
{% load my_filter %}
{% block cssadd %}
<link rel="stylesheet" href="{% static 'horoscope_app/css/index.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}
    <h1>{{ element.name }}</h1>
    <ul class="ul-style-1">
    {% for item in elements %}
        <li class='ul-li'><a class="btn btn-outline-dark" href="{% url 'sign_zodiac' code=item.code %}">{{ item.name }}</a></li>
    {% endfor %}
{% endblock %}

horoscope_app/templates/horoscope_app/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% load static %}
{% load my_filter %}

{% block cssadd %}
<link rel="stylesheet" href="{% static 'horoscope_app/css/index.css' %}">
{% endblock %}


{% block content %}
{% include 'includes/navbar.html' %}
<div class="container-fluid">
    <h2>Гороскоп для всех знаков на {{ today }}</h2>
    <p>{{ forecast_general.description }}</p>
    <h2>Индивидуалный гороскоп для каждого знака</h2>
    <ul class="ul-style">
        {% for zodiac_sing in zodiaksing_list %}

        <li class='ul-li'><a class="btn btn-outline-dark" href="{% url 'sign_zodiac' code=zodiac_sing.code %}">{{zodiac_sing.name}}</a>
        </li>

        {% endfor %}
    </ul>
</div>

{% endblock %}

horoscope_app/templates/horoscope_app/info_zodiac.html
{% extends 'base.html' %}


{% block title %}
{{sign.title}}
{% endblock %}

{% load static %}
{% load my_filter %}
{% block cssadd %}
<link rel="stylesheet" href="{% static 'horoscope_app/css/index.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}
    <h1>{{ zodiac_sing.name }}</h1>
    <p>{{ zodiac_sing.description}}</p>
    <h2>Прогноз на сегоня</h2>
    <p>{{ forecast_zodiac_sing.description }}</p>

{% endblock %}